// Every key a control asks for must be in the list the package ships.
//
// `translation-keys.json` is generated by scanning the sources for `t('literal')`, and a host
// translates by reading it. A key assembled at runtime - from a switch, a ternary, a variable -
// is invisible to that scan, so it never reaches the list, no host knows to translate it, and it
// arrives at the user as itself. The generator's own comment says as much; this asserts it of
// the controls rather than of the regex.
//
// The one legitimate exception is a key the HOST supplied in the first place: a control told to
// offer a set of trading modes words each one through `t()`, and those strings are the host's
// vocabulary, not the package's. Such keys are named per control below, so the exception is
// declared rather than assumed.
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { asDom, el, installFakeDom } from './fake-dom.js';
import { fakeHost } from './fake-host.js';
import { StrategiesWidget, StrategyStates } from '../src/strategies-widget.js';
import { LogMonitorWidget } from '../src/log-monitor-widget.js';
import { OptionDeskWidget } from '../src/option-desk-widget.js';
import { StatisticsWidget } from '../src/statistics-widget.js';
import { LogLevels } from '../src/log-tree.js';

installFakeDom();

const SHIPPED: string[] = JSON.parse(readFileSync('translation-keys.json', 'utf8')).keys;

/// A host that answers like any other and remembers what it was asked.
function recordingHost() {
    const host = fakeHost();
    const asked: string[] = [];
    const inner = host.t;
    host.t = (key: string, ...args: unknown[]) => {
        asked.push(key);
        return inner(key, ...args);
    };
    return { host, asked };
}

function assertShipped(asked: readonly string[], hostVocabulary: readonly string[], what: string): void {
    const missing = [...new Set(asked)]
        .filter(key => !SHIPPED.includes(key) && !hostVocabulary.includes(key))
        .sort();

    assert.deepStrictEqual(missing, [], `${what} asks for keys the package does not ship: ${missing.join(', ')}`);
}

describe('the shipped key list', () => {
    it('carries every state a strategy row can be in', () => {
        const { host, asked } = recordingHost();
        const modes = ['Full', 'CancelOrders', 'Disabled'];
        const widget = StrategiesWidget.create(asDom(el('div')), {}, {
            host,
            tradingModes: modes,
            start: () => { }, stop: () => { }, closePosition: () => { },
            openStrategy: () => { }, setTradingMode: () => { },
        });

        // Every state, so every branch of the wording is taken.
        widget.update(Object.values(StrategyStates).map((state, i) => ({
            id: `s${i}`, name: `Strategy ${i}`, state,
            portfolio: 'Sim', security: 'BTC@IMEX', position: 1,
            ordersCount: 1, tradesCount: 1, pnlChange: 0, realized: 0, unrealized: 0,
            tradingMode: 'Full',
        })));

        assertShipped(asked, modes, 'StrategiesWidget');
    });

    it('carries every level a log message can carry', () => {
        const { host, asked } = recordingHost();
        const widget = LogMonitorWidget.create(asDom(el('div')), {}, { host });

        widget.setSources([{ id: 'root', name: 'Root' }]);
        widget.append(Object.values(LogLevels).map((level, i) => ({
            id: i, time: '2024-03-01T10:00:00Z', level, sourceId: 'root', message: `line ${i}`,
        })));

        assertShipped(asked, [], 'LogMonitorWidget');
    });

    it('carries both sides of an option chain', () => {
        const { host, asked } = recordingHost();
        const widget = OptionDeskWidget.create(asDom(el('div')), {}, { host });

        widget.update([{
            strike: 100,
            call: { symbol: 'C100', bid: 5, ask: 5.4, ivLast: 0.2 },
            put: { symbol: 'P100', bid: 4.8, ask: 5.1, ivLast: 0.21 },
        }], { assetPrice: 100, timeToExpiry: 0.5, riskFree: 0.05, dividend: 0 });

        assertShipped(asked, [], 'OptionDeskWidget');
    });

    it('carries what a statistics table says', () => {
        const { host, asked } = recordingHost();
        const widget = StatisticsWidget.create(asDom(el('div')), {}, { host });

        widget.update([{ key: 'NetProfit', category: 'pnl', categoryText: 'P&L', order: 1, name: 'Net profit', value: 1 }]);

        assertShipped(asked, [], 'StatisticsWidget');
    });
});
